# 1) Build-Phase
FROM node:22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# 2) Production-Server
FROM nginx:alpine

# Nginx Config kopieren
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Build Output kopieren
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
