services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      GITHUB_CLIENT_ID: "Ov23livXgBq4ImJhZMyP"
      GITHUB_CLIENT_SECRET: "08d900f5163d419c268265cf48c4fb6d2bbaab34"
      GITHUB_REDIRECT_URI: "http://localhost:3000/auth/github/callback"
    volumes:
      - ./Backend/database.sqlite:/app/database.sqlite
