server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # SPA Routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets normal ausliefern
    location /assets/ {
        try_files $uri =404;
    }
}
