FROM node:22

WORKDIR /app

# Nur package.json kopieren
COPY package*.json ./

# Linux-kompatible node_modules installieren
RUN npm install

# Jetzt den Rest kopieren
COPY . .

# Die SQLite-Datenbank INS Image kopieren
COPY database.sqlite /app/database.sqlite


EXPOSE 3000

CMD ["node", "index.js"]
