FROM node:22

WORKDIR /app

# Nur package.json kopieren
COPY package*.json ./

# Linux-kompatible node_modules installieren
RUN npm install

# Jetzt den Rest kopieren
COPY . .

EXPOSE 3000

CMD ["node", "index.js"]
